<a href="https://colab.research.google.com/github/sharvadlamani/ml-colab-notebooks/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
print(vector.ndim)
# think number of closing square brackets
vector.shape

1


torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR[0][1]

tensor([3, 6, 9])

### Random Tensors

Why random tensors? Many neural networks start with tensors full of random numbers and update them.

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0425, 0.0028, 0.4441, 0.9087],
        [0.8710, 0.9798, 0.3368, 0.1629],
        [0.0121, 0.2766, 0.0665, 0.3183]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros
#

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Creating a range of tensors and tensors-like


In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
another_range = torch.arange(start=0, end=1000, step= 77)
another_range

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None,
                               requires_grad=False) #whether or not to track gradients with this tensor's operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

get datatype using tensor.dtype
shape: tensor.shape
device: tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6601, 0.0247, 0.3302, 0.6162],
        [0.2382, 0.0541, 0.4968, 0.5730],
        [0.3604, 0.1591, 0.1364, 0.5774]])

In [ ]:
#find out details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.6601, 0.0247, 0.3302, 0.6162],
        [0.2382, 0.0541, 0.4968, 0.5730],
        [0.3604, 0.1591, 0.1364, 0.5774]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


In [ ]:
### Manipulating tensors
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor, tensor.shape

tensor + 10, tensor


(tensor([11, 12, 13]), tensor([1, 2, 3]))

In [ ]:
tensor * 10, tensor

(tensor([10, 20, 30]), tensor([1, 2, 3]))

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor
# @ is same as matrix multiplication

tensor(14)

Matrix Multiplication rules:
* Inner dimensions must MATCH
* The resulting matrix has the shape of the OUTER dimensions. For example (2,3) @ (3,2) will result in a shape of (2,2)

In [ ]:
tensor = torch.tensor([[1,2, 3],[4,5,6]])
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.T, tensor.T.shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 torch.Size([3, 2]))

In [ ]:
tensor.matmul(tensor.T), tensor.matmul(tensor.T).shape

(tensor([[14, 32],
         [32, 77]]),
 torch.Size([2, 2]))

In [ ]:
### Tensor Aggregation
# Finding the mean, min, max, etc.
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
#

(tensor(46.), tensor(46.))

In [ ]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [ ]:
### Finding hte positional min or max


In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

In [ ]:
# Reshaping, stacking, squeezing, and unsqueezing